/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xuetenglong_kotlindemo_utils_CalculateUtils */

#ifndef _Included_com_example_xuetenglong_kotlindemo_utils_CalculateUtils
#define _Included_com_example_xuetenglong_kotlindemo_utils_CalculateUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xuetenglong_kotlindemo_utils_CalculateUtils
 * Method:    getStringFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xuetenglong_kotlindemo_utils_CalculateUtils_getStringFromNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
